services:

  db:
    image: postgres
    container_name: postgres_data_science
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
